on:
  push:
    branches: [CI]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: cypress run
        continue-on-error: true
        uses: cypress-io/github-action@v2
        with:
          install-command: npm install
          browser: chrome

      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./TestReport

  


  
