on:
  push:
    branches: [CI]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Instalar dependências
        run: npm install

      - name: Executar testes com Cypress
        continue-on-error: true
        uses: cypress-io/github-action@v2
        with:
          install-command: npm install
          config-file: cypress.config.js
          browser: chrome

      - name: Renomear Report.html para index.html
        run: mv TestReport/Report.html TestReport/index.html

      - name: Publicar relatório no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./TestReport


  


  
